from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("graphs/", views.graphs, name="graphs"),
    path("api/wallets/", views.wallet_balances_api, name="api_wallets"),
    path("api/scan-receipt/", views.api_scan_receipt, name="api_scan_receipt"),
    path("wallets/", views.wallet_list, name="wallet_list"),
    path("wallets/reorder/", views.wallet_reorder, name="wallet_reorder"),
    path("wallets/new/", views.wallet_create, name="wallet_create"),
    path("wallets/<int:pk>/edit/", views.wallet_edit, name="wallet_edit"),
    path("wallets/<int:pk>/toggle/", views.wallet_toggle_archive, name="wallet_toggle_archive"),
    path("wallets/<int:pk>/toggle-total/", views.wallet_toggle_total, name="wallet_toggle_total"),
    path("wallets/<int:pk>/delete/", views.wallet_delete, name="wallet_delete"),
    path("categories/", views.category_list, name="category_list"),
    path("categories/new/", views.category_create, name="category_create"),
    path("categories/<int:pk>/edit/", views.category_edit, name="category_edit"),
    path("categories/<int:pk>/delete/", views.category_delete, name="category_delete"),
    path("transactions/", views.transaction_list, name="transaction_list"),
    path("transactions/new/", views.transaction_create, name="transaction_create"),
    path("transactions/<int:pk>/edit/", views.transaction_edit, name="transaction_edit"),
    path("transactions/<int:pk>/delete/", views.transaction_delete, name="transaction_delete"),
    path("subscriptions/", views.subscription_list, name="subscription_list"),
    path("subscriptions/new/", views.subscription_create, name="subscription_create"),
    path("subscriptions/<int:pk>/edit/", views.subscription_edit, name="subscription_edit"),
    path("subscriptions/<int:pk>/delete/", views.subscription_delete, name="subscription_delete"),
    path("subscriptions/<int:pk>/pay/", views.subscription_pay, name="subscription_pay"),
    path("subscriptions/<int:pk>/undo/", views.subscription_undo, name="subscription_undo"),
    path("subscriptions/<int:pk>/payments/<int:payment_pk>/delete/", views.subscription_payment_delete, name="subscription_payment_delete"),
    path("debts/", views.debt_list, name="debt_list"),
    path("debts/new/", views.debt_create, name="debt_create"),
    path("debts/<int:pk>/edit/", views.debt_edit, name="debt_edit"),
    path("debts/<int:pk>/delete/", views.debt_delete, name="debt_delete"),
    path("debts/<int:pk>/pay/", views.debt_payment_create, name="debt_payment_create"),
    path("debts/<int:pk>/settle/", views.debt_settle, name="debt_settle"),
    path("debts/<int:pk>/payments/<int:payment_pk>/delete/", views.debt_payment_delete, name="debt_payment_delete"),
    path("budgets/set/", views.budget_set, name="budget_set"),
    path("export/csv/", views.export_csv, name="export_csv"),
    path("more/", views.more_view, name="more"),
    path("profile/", views.profile_edit_view, name="profile_edit"),
    path("profile/remove-avatar/", views.profile_remove_avatar, name="profile_remove_avatar"),
    path("offline/", views.offline_view, name="offline"),
    path("sw.js", views.service_worker, name="service_worker"),
]
