# Generated by Django 5.2.17 on 2026-08-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='label', max_length=32),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='icon',
            field=models.CharField(default='account_balance_wallet', max_length=32),
        ),
    ]
