# Generated by Django 5.2.17 on 2026-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='include_in_total',
            field=models.BooleanField(default=True, help_text='Include in total balance calculation'),
        ),
    ]
