# Generated by Django 5.2.17 on 2026-09-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_transaction_image_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='due_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month when due (1-12, for yearly subscriptions)', null=True),
        ),
    ]
