# Generated by Django 5.2.17 on 2026-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_subscription_due_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='wallet',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
