# Generated by Django 5.2.17 on 2026-09-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_wallet_options_wallet_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_paid_date',
            field=models.DateField(blank=True, help_text='Date when this subscription was last paid', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank/Debit'), ('ewallet', 'E-Wallet'), ('savings', 'Savings'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
