# Generated by Django 5.2.17 on 2026-09-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_debt_debtpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payment', to='tracker.transaction'),
        ),
    ]
