# Generated by Django 5.2.17 on 2026-09-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_debtpayment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_origin', to='tracker.transaction'),
        ),
    ]
