# Generated by Django 5.2.17 on 2026-09-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='already_paid_installments',
            field=models.PositiveSmallIntegerField(default=0, help_text='Installments already paid prior to tracking in this app'),
        ),
    ]
