# Generated by Django 5.2.17 on 2026-09-30 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_profiles(apps, schema_editor):
    UserProfile = apps.get_model('tracker', 'UserProfile')
    UserProfile.objects.all().update(is_approved=True, approval_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_transaction_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved by an administrator.'),
        ),
        migrations.RunPython(approve_existing_profiles, migrations.RunPython.noop),
    ]
