# Generated by Django 5.2.17 on 2026-10-03 06:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_userprofile_approval_status_userprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total target amount / contract principal (optional)', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Designates whether this user has been approved by an administrator.'),
        ),
    ]
