# Generated by Django 5.2.17 on 2026-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_transactiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional savings goal target amount', max_digits=14, null=True),
        ),
    ]
